//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiaShop.Loja.Assets.Templates._1.ascx {
    
    
    /// <summary>
    /// Rodape class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Rodape {
        
        /// <summary>
        /// Metodos_Pagamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.IconesRodape Metodos_Pagamento;
        
        /// <summary>
        /// PaginasInstitucionais control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.PaginasInstitucionais PaginasInstitucionais;
        
        /// <summary>
        /// link_afiliados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link link_afiliados;
        
        /// <summary>
        /// Duvidas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link Duvidas;
        
        /// <summary>
        /// Fale_Conosco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link Fale_Conosco;
        
        /// <summary>
        /// selo_rodape_ciashop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link selo_rodape_ciashop;
        
        /// <summary>
        /// selo_rodape_fcontrol control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link selo_rodape_fcontrol;
        
        /// <summary>
        /// selo_rodape_ebit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.EbitBanner selo_rodape_ebit;
    }
}
