//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiaShop.Loja.Assets.Templates._1.ascx {
    
    
    public partial class TopoListaPresente {
        
        /// <summary>
        /// PaginaInicial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link PaginaInicial;
        
        /// <summary>
        /// LinkListaPresentes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link LinkListaPresentes;
        
        /// <summary>
        /// LinkMeuCadastro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link LinkMeuCadastro;
        
        /// <summary>
        /// LinkMeusPedidos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link LinkMeusPedidos;
        
        /// <summary>
        /// LinkCarrinhoCompras control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.Link LinkCarrinhoCompras;
        
        /// <summary>
        /// LabelVisitante1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.LabelVisitante LabelVisitante1;
        
        /// <summary>
        /// ListaPresentesTopo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ciashop.Publica.Componente.Loja.ListaPresentesTopo ListaPresentesTopo1;
    }
}
